# Task 1
## Виконати набір вправ. Всі завдання виконати 2 способами:
 <li>з використанням універсальних функцій бібліотеки NumPy</li>
 <li>b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо.</li>

In [4]:
import math
import random
import numpy as np

## Вправа 1
### Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [6]:
def task_1():
    n = int(input("Enter n: "))
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        arr[i][i] = i + 1

    for row in arr:
        print(row)
        
        
%time task_1()

Enter n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: total: 0 ns
Wall time: 2.67 s


In [7]:
import numpy as np

def task_1():
    n = int(input("Enter n: "))
    arr = np.zeros((n, n), dtype=int)
    arr[np.diag_indices_from(arr)] = np.arange(1, n+1)
    print(arr)


%time task_1()

Enter n:  5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
CPU times: total: 15.6 ms
Wall time: 1.65 s


## Вправа 3
### Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [10]:
def task_3():
    input_str = input("Enter n, m, r, c separated by space: ")
    values = input_str.split()
    n, m, r, c = map(int, values)
    
    arr = [[1 for j in range(m)] for i in range(n)]
    
    for i in range(n):
        if i % r == 0:
            arr[i] = [0 for j in range(m)]

    for i in range(m):
        if i % c == 0:
            for j in range(n):
                arr[j][i] = 0
        
    for row in arr:
        print(row)
        
%time task_3()

Enter n, m, r, c separated by space:  6 7 2 3


[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
CPU times: total: 15.6 ms
Wall time: 13.4 s


In [12]:
import numpy as np

def task_3():
    input_str = input("Enter n, m, r, c separated by space: ")
    values = input_str.split()
    n, m, r, c = map(int, values)
    
    arr = np.ones((n, m), dtype=int)
    arr[::r, :] = 0
    arr[:, ::c] = 0

    print(arr)
    
%time task_3()

Enter n, m, r, c separated by space:  6 7 2 3


[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: total: 0 ns
Wall time: 3.01 s


## Вправа 4
### Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [16]:
def task_4():
    input_str = input("Enter n, m separated by space: ")
    values = input_str.split()
    n, m = map(int, values)
    
    arr = [[0 for j in range(n)] for i in range(m)]
    
    for i in range(n):
        arr[0][i] = i
        
    for row in arr:
        print(row)
        
%time task_4()

Enter n, m separated by space:  3 4


[0, 1, 2]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
CPU times: total: 0 ns
Wall time: 2.42 s


In [20]:
import numpy as np

def task_4():
    input_str = input("Enter n, m separated by space: ")
    values = input_str.split()
    n, m = map(int, values)
    
    arr = np.zeros((m, n), dtype=int)
    
    arr[0] = np.arange(n)
    
    print(arr)
    
%time task_4()

Enter n, m separated by space:  3 4


[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
CPU times: total: 0 ns
Wall time: 2.89 s


## Вправа 6
### З клавіатури вводиться масив, Замінити всі ненульові елементи на -1.

In [25]:
def task_6(input_array):
    for i in range(len(input_array)):
        if input_array[i] != 0:
            input_array[i] = -1
    return input_array

%time task_6([3,4,0,9,7,0,6,0,4,0,3])

CPU times: total: 0 ns
Wall time: 0 ns


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]

In [26]:
import numpy as np

def task_6(input_array):
    arr = np.array(input_array)
    arr[arr != 0] = -1
    return arr

%time task_6([3,4,0,9,7,0,6,0,4,0,3])

CPU times: total: 0 ns
Wall time: 0 ns


array([-1, -1,  0, -1, -1,  0, -1,  0, -1,  0, -1])

## Вправа 10
### Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [28]:
import random
import math

def task_10():
    input_str = input("Enter n, m separated by space: ")
    values = input_str.split()
    n, m = map(int, values)
    
    arr = [[round(random.uniform(0, 1), 3) for j in range(m)] for i in range(n)]

    arr_min = min(min(arr[i]) for i in range(n))
    arr_max = max(max(arr[i]) for i in range(n))

    sum_val = sum(sum(arr[i]) for i in range(n))
    arr_mean = sum_val / (n * m)

    sq_diff = sum((arr[i][j] - arr_mean) ** 2 for i in range(n) for j in range(m))
    arr_std = math.sqrt(sq_diff / (n * m))

    print(f"мінімум: {arr_min}")
    print(f"максимум: {arr_max}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")

%time task_10()

Enter n, m separated by space:  4 5


мінімум: 0.087
максимум: 0.976
середнє: 0.579
дисперсія: 0.260
CPU times: total: 15.6 ms
Wall time: 6.26 s


In [29]:
import random
import math
import numpy as np

def task_4():
    input_str = input("Enter n, m separated by space: ")
    values = input_str.split()
    n, m = map(int, values)
    
    arr = np.random.rand(n, m)
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    
    print(f"мінімум: {arr_min}")
    print(f"максимум: {arr_max}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")
    
%time task_10()   

Enter n, m separated by space:  4 5


мінімум: 0.061
максимум: 0.988
середнє: 0.523
дисперсія: 0.257
CPU times: total: 15.6 ms
Wall time: 3.91 s


## Вправа 12
### Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [31]:
def task_12():
    n = int(input("Enter n: "))
    
    arr = [[1 for j in range(n)] for i in range(n)]
    
    arr[0] = [0 for i in range(n)]
    arr[n-1] = [0 for i in range(n)]
    
    for i in range(1, n-1):
        for j in range(n):
            if j == 0 or j == n - 1:
                arr[i][j] = 0
                
    for row in arr:
        print(row)
        
%time task_12()

Enter n:  4


[0, 0, 0, 0]
[0, 1, 1, 0]
[0, 1, 1, 0]
[0, 0, 0, 0]
CPU times: total: 15.6 ms
Wall time: 4.44 s


In [32]:
import numpy as np

def task_12():
    n = int(input("Enter n: "))
    
    arr = np.ones((n, n), dtype=int)
    
    arr[::n-1, :] = 0
    arr[:, ::n-1] = 0

    print(arr)
    
%time task_12()

Enter n:  4


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
CPU times: total: 0 ns
Wall time: 2.03 s


## Вправа 15
### Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [70]:
def task_15(n):
    matrix = [[1 if col % 2 == 0 else 0 for col in range(n)] for row in range(n)]
    return matrix

%timeit task_15(5)

2.17 µs ± 80 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [68]:
import numpy as np

def task_15(n):
    matrix = np.zeros((n, n))
    matrix[:, ::2] = 1
    return matrix

%timeit task_15(5)

785 ns ± 17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Вправа 17
### Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [33]:
def task_17():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if i < n/2 or i > 3*n/4:
            arr[i] *= -1
            
    print(arr)
        
%time task_17()

Enter n:  10


[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
CPU times: total: 15.6 ms
Wall time: 1.77 s


In [34]:
import numpy as np

def task_17():
    n = int(input("Enter n: "))
    
    arr = np.arange(n+1)
    arr[(arr < n/2) | (arr > 3*n/4)] *= -1
    
    print(arr)
    
%time task_17()

Enter n:  10


[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
CPU times: total: 0 ns
Wall time: 1.64 s


## Вправа 18 
### Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [60]:
def task_18(n):
    array = []
    for i in range(n):
        array.append(random.randint(0, 100))
    print(array)
    list_set = set(array)
    return len(list_set)

%time print("unique values: ", task_18(30))

[49, 66, 96, 5, 90, 56, 79, 0, 36, 8, 0, 58, 73, 48, 32, 46, 71, 3, 56, 1, 20, 76, 73, 29, 42, 50, 97, 74, 38, 54]
unique values:  27
CPU times: total: 0 ns
Wall time: 0 ns


In [52]:
import numpy as np

def task_18(n):
    array = np.random.randint(0, 100, n)
    print(array)
    return len(np.unique(array))

%time print("unique values: ", task_18(30))

[99 92 92  2 52 44 17  0 80 74 56 41 90 62 62  1 70 32 93 99 31 13 57 30
 29 17 44 86 46 24]
unique values:  25
CPU times: total: 0 ns
Wall time: 1 ms


# Task 2

## Завдання 2
### Розв'язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
- матричного множення
- оберненої матриці
- функції numpy.linalg.solve()

### Порівняти всі рішення за допомогою функції numpy.allclose().
### Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:

\[
\begin{align*}
1x_1 + 5x_2 + 3x_3 - 4x_4 &= 20 \\
3x_1 + 1x_2 - 2x_3 + 0x_4 &= 9 \\
5x_1 - 7x_2 + 0x_3 + 10x_4 &= -9 \\
0x_1 + 3x_2 - 5x_3 + 0x_4 &= 1 \\
\end{align*}
\]
нь та розв'язок:

### Порівняти всі рішення за допомогою функції numpy.allclose().

### Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:

In [77]:
left = np.array([
    [1, 5, 3, -4],
    [3,  1,  -2, 0],
    [5, -7, 0, 10],
    [0, 3, -5, 0]
])

right = np.array([20, 9, -9, 1])


def cramers_solve(left, right):
    length = len(right)
    determinant = np.linalg.det(left)
    solution = np.zeros(length)
    
    if np.allclose(determinant, 0):
        print("Determinant is zero, there's no solution of given equation.")
        return solution
    
    for i in range(length):
        modified_left = np.copy(left)
        modified_left[:, i] = np.copy(right)
        solution[i] = np.linalg.det(modified_left) / determinant
    
    return solution

cramer_result = cramers_solve(left, right)
numpy_result = np.linalg.solve(left, right)
multiplication_check = np.dot(left, cramer_result)
inverse_matrix_check = np.dot(np.linalg.inv(left), right)

print(f"Result of Cramer's method: {cramer_result}") 
print(f"Result of using numpy.linalg.solve(): {numpy_result}")
print(f"Check results: {np.allclose(numpy_result, cramer_result)}\n")

print(f"Check using matrix multiplication: {np.allclose(right, multiplication_check)}")
print(f"Check using inverse matrix: {np.allclose(inverse_matrix_check, cramer_result)}")

Result of Cramer's method: [ 3.  2.  1. -1.]
Result of using numpy.linalg.solve(): [ 3.  2.  1. -1.]
Check results: True

Check using matrix multiplication: True
Check using inverse matrix: True


# Task 3

# Обчислити значення матричного виразу
$$
(A - B^2)(2A + B), \quad A = 
\begin{bmatrix}
    5 & 2 & 0 \\
    10 & 4 & 1 \\
    7 & 3 & 2 \\
\end{bmatrix},
\quad B = 
\begin{bmatrix}
    3 & 6 & -1 \\
    -1 & -2 & 0 \\
    2 & 1 & 3 \\
\end{bmatrix}
$$
bmatrix}
\]


- з використанням універсальних функцій бібліотеки NumPy.
- за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
- для обох випадків підрахувати час виконання скрипту та
зробити висновок.

In [89]:
A = [[5, 2, 0],
     [10, 4, 1],
     [7, 3, 2]]

B = [[3, 6, -1],
     [-1, -2, 0],
     [2, 1, 3]]

A_np = np.array(A)
B_np = np.array(B)


def multiplication(A, B):
    a_rows, a_columns, b_rows, b_columns = len(A), len(A[0]), len(B), len(B[0])
    result = []
    if a_columns != b_rows:
        print("Multiplication cannot be done because of different dimensions.")
        return result
    
    for i in range(a_rows):
        new_row = []
        for j in range(b_columns):
            element_sum = 0
            for k in range(a_columns):
                element_sum += A[i][k] * B[k][j]
            new_row.append(element_sum)
        result.append(new_row)
    
    return result
    
def addition(A, B):
    a_rows, a_columns, b_rows, b_columns = len(A), len(A[0]), len(B), len(B[0])
    result = []
    if a_rows != b_rows or a_columns != b_columns:
        print("Addition cannot be done because of different dimensions.")
        return result
    
    for i in range(a_rows):
        new_row = []
        for j in range(a_columns):
            new_row.append(A[i][j] + B[i][j])
        result.append(new_row)
    
    return result

def scalar_multiplication(a, A):
    result = []
    for i in range(len(A)):
        new_row = []
        for j in range(len(A[0])):
            new_row.append(A[i][j] * a)
        result.append(new_row)
        
    return result

In [96]:
%%timeit -n 100 -r 10
numpy_result = (A_np - B_np @ B_np) @ (2 * A_np + B_np)

4.4 µs ± 1.12 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [99]:
%%timeit -n 100 -r 10
iterative_result = multiplication(addition(A, multiplication(scalar_multiplication(-1, B), B)), addition(scalar_multiplication(2, A), B))

10.8 µs ± 1.54 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [100]:
numpy_result = (A_np - B_np @ B_np) @ (2 * A_np + B_np)
iterative_result = multiplication(addition(A, multiplication(scalar_multiplication(-1, B), B)), addition(scalar_multiplication(2, A), B))
np.allclose(numpy_result, iterative_result)

True